factories:
  model:
    ModelFactory: {}

  loss: 
    LossFactory: {}
                          
  miner: 
    MinerFactory: {}

  sampler:
    SamplerFactory: {}

  optimizer:
    OptimizerFactory:
      param_sources:
        - models
        - loss_funcs

  tester:
    TesterFactory: {}

  trainer:
    TrainerFactory: {}

  transform:
    TransformFactory: {}

  split_manager:
    SplitManagerFactory: {}

  record_keeper:
    RecordKeeperFactory: {}

  hook:
    HookFactory: {}